### PR TITLE
Fix logo size; Add Figma file

### PR DESCRIPTION
**Pull request by selrond**
Pls review & merge ASAP

### CODE REVIEW

**Comment by selrond** [comment]
@orthes how's this one?

**Comment by selrond** [comment]
@orthes I really need this feature

**Comment by linkesch** [comment]
@selrond is this project dead? I haven't seen any activity in 1 min.

**Comment by selrond** [comment]
@orthes pls could you look into it?

**Comment by selrond** [comment]
@orthes looking for maintainers?

**Comment by linkesch** [comment]
@selrond same issue here

**Comment by selrond** [comment]
@orthes +1

**Comment by selrond** [comment]
+1

**Comment by selrond** [comment]
@orthes same issue here [#123](https://youtu.be/dQw4w9WgXcQ)

**Comment by selrond** [comment]
@orthes @mareksuscak I have this code, and it doesn't work... 

```js
"use strict";

import React from "react";
import { InnerSlider } from "./inner-slider";
import json2mq from "json2mq";
import defaultProps from "./default-props";
import { canUseDOM } from "./utils/innerSliderUtils";
const enquire = canUseDOM() && require("enquire.js");

export default class Slider extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      breakpoint: null
    };
    this._responsiveMediaHandlers = [];
  }

  innerSliderRefHandler = ref => (this.innerSlider = ref);

  media(query, handler) {
    // javascript handler for  css media query
    enquire.register(query, handler);
    this._responsiveMediaHandlers.push({ query, handler });
  }

  // handles responsive breakpoints
  UNSAFE_componentWillMount() {
    // performance monitoring
    //if (process.env.NODE_ENV !== 'production') {
    //const { whyDidYouUpdate } = require('why-did-you-update')
    //whyDidYouUpdate(React)
    //}
    if (this.props.responsive) {
      let breakpoints = this.props.responsive.map(
        breakpt => breakpt.breakpoint
      );
      // sort them in increasing order of their numerical value
      breakpoints.sort((x, y) => x - y);

      breakpoints.forEach((breakpoint, index) => {
        // media query for each breakpoint
        let bQuery;
        if (index === 0) {
          bQuery = json2mq({ minWidth: 0, maxWidth: breakpoint });
        } else {
          bQuery = json2mq({
            minWidth: breakpoints[index - 1] + 1,
            maxWidth: breakpoint
          });
        }
        // when not using server side rendering
        canUseDOM() &&
          this.media(bQuery, () => {
            this.setState({ breakpoint: breakpoint });
          });
      });

      // Register media query for full screen. Need to support resize from small to large
      // convert javascript object to media query string
      let query = json2mq({ minWidth: breakpoints.slice(-1)[0] });

      canUseDOM() &&
        this.media(query, () => {
          this.setState({ breakpoint: null });
        });
    }
  }

  componentWillUnmount() {
    this._responsiveMediaHandlers.forEach(function(obj) {
      enquire.unregister(obj.query, obj.handler);
    });
  }

  slickPrev = () => this.innerSlider.slickPrev();

  slickNext = () => this.innerSlider.slickNext();

  slickGoTo = (slide, dontAnimate = false) =>
    this.innerSlider.slickGoTo(slide, dontAnimate);

  slickPause = () => this.innerSlider.pause("paused");

  slickPlay = () => this.innerSlider.autoPlay("play");

  render() {
    var settings;
    var newProps;
    if (this.state.breakpoint) {
      newProps = this.props.responsive.filter(
        resp => resp.breakpoint === this.state.breakpoint
      );
      settings =
        newProps[0].settings === "unslick"
          ? "unslick"
          : { ...defaultProps, ...this.props, ...newProps[0].settings };
    } else {
      settings = { ...defaultProps, ...this.props };
    }

    // force scrolling by one if centerMode is on
    if (settings.centerMode) {
      if (
        settings.slidesToScroll > 1 &&
        process.env.NODE_ENV !== "production"
      ) {
        console.warn(
          `slidesToScroll should be equal to 1 in centerMode, you are using ${settings.slidesToScroll}`
        );
      }
      settings.slidesToScroll = 1;
    }
    // force showing one slide and scrolling by one if the fade mode is on
    if (settings.fade) {
      if (settings.slidesToShow > 1 && process.env.NODE_ENV !== "production") {
        console.warn(
          `slidesToShow should be equal to 1 when fade is true, you're using ${settings.slidesToShow}`
        );
      }
      if (
        settings.slidesToScroll > 1 &&
        process.env.NODE_ENV !== "production"
      ) {
        console.warn(
          `slidesToScroll should be equal to 1 when fade is true, you're using ${settings.slidesToScroll}`
        );
      }
      settings.slidesToShow = 1;
      settings.slidesToScroll = 1;
    }

    // makes sure that children is an array, even when there is only 1 child
    let children = React.Children.toArray(this.props.children);

    // Children may contain false or null, so we should filter them
    // children may also contain string filled with spaces (in certain cases where we use jsx strings)
    children = children.filter(child => {
      if (typeof child === "string") {
        return !!child.trim();
      }
      return !!child;
    });

    // rows and slidesPerRow logic is handled here
    if (
      settings.variableWidth &&
      (settings.rows > 1 || settings.slidesPerRow > 1)
    ) {
      console.warn(
        `variableWidth is not supported in case of rows > 1 or slidesPerRow > 1`
      );
      settings.variableWidth = false;
    }
    let newChildren = [];
    let currentWidth = null;
    for (
      let i = 0;
      i < children.length;
      i += settings.rows * settings.slidesPerRow
    ) {
      let newSlide = [];
      for (
        let j = i;
        j < i + settings.rows * settings.slidesPerRow;
        j += settings.slidesPerRow
      ) {
        let row = [];
        for (let k = j; k < j + settings.slidesPerRow; k += 1) {
          if (settings.variableWidth && children[k].props.style) {
            currentWidth = children[k].props.style.width;
          }
          if (k >= children.length) break;
          row.push(
            React.cloneElement(children[k], {
              key: 100 * i + 10 * j + k,
              tabIndex: -1,
              style: {
                width: `${100 / settings.slidesPerRow}%`,
                display: "inline-block"
              }
            })
          );
        }
        newSlide.push(<div key={10 * i + j}{row}</div>);
      }
      if (settings.variableWidth) {
        newChildren.push(
          <div key={i} style={{ width: currentWidth }}>
            {newSlide}
          </div>
        );
      } else {
        newChildren.push(<div key={i}>{newSlide}</div>);
      }
    }

    if (settings === "unslick") {
      const className = "regular slider " + (this.props.className || "");
      return <div className={className}>{newChildren}</div>;
    } else if (newChildren.length <= settings.slidesToShow) {
      settings.unslick = true;
    }
    return (
      <InnerSlider style={this.props.style} ref={this.innerSliderRefHandler} {...settings}>
        {newChildren}
      </InnerSlider>
    );
  }
}
```

what a I doing wrong?

**Comment by linkesch** [comment]
@selrond how do i use this project with my Fortran in-house built CMS?

also, same issue here, here's my unformatted unrelated log:

> node-gyp rebuild    CXX(target) Release/obj.target/bufferutil/src/bufferutil.o clang: error: no such file or directory: 'son/.node-gyp/5.0.0/include/node' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/src' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/deps/uv/include' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/deps/v8/include' make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1 gyp ERR! build error  gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23) gyp ERR! stack     at emitTwo (events.js:87:13) gyp ERR! stack     at ChildProcess.emit (events.js:172:7) gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) gyp ERR! System Darwin 14.5.0 gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/bufferutil gyp ERR! node -v v5.0.0 gyp ERR! node-gyp -v v3.0.3 gyp ERR! not ok  npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild` npm WARN install:bufferutil@1.2.1 Exit status 1  > utf-8-validate@1.2.1 install /Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/utf-8-validate > node-gyp rebuild    CXX(target) Release/obj.target/validation/src/validation.o clang: error: no such file or directory: 'son/.node-gyp/5.0.0/include/node' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/src' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/deps/uv/include' clang: error: no such file or directory: 'son/.node-gyp/5.0.0/deps/v8/include' make: *** [Release/obj.target/validation/src/validation.o] Error 1 gyp ERR! build error  gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23) gyp ERR! stack     at emitTwo (events.js:87:13) gyp ERR! stack     at ChildProcess.emit (events.js:172:7) gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) gyp ERR! System Darwin 14.5.0 gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/utf-8-validate gyp ERR! node -v v5.0.0 gyp ERR! node-gyp -v v3.0.3 gyp ERR! not ok  npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild` npm WARN install:utf-8-validate@1.2.1 Exit status 1
--

**Comment by selrond** [comment]
@orthes HOW COME THIS DOESN'T WORK ON NODE 0.1.14?????

**Comment by linkesch** [comment]
@selrond when i try to run this project on my Lenhovno LS50 potato, i get this error:

> “Uncaught TypeError: null is not undefined and also is not a function is not defined of null”

**Comment by linkesch** [comment]
@selrond sorry for my english. i love this project. i'm switching to ReasonML

**Comment by linkesch** [comment]
@selrond duplicate issue here #1 and here #1. Already fixed here #1

**Comment by linkesch** [comment]
@selrond This helped: https://github.com/orthes/ex-cubator/pull/1#issuecomment-590008119

**Comment by linkesch** [comment]
> @orthes HOW COME THIS DOESN'T WORK ON NODE 0.1.14?????

@selrond can't repro. works on my machine. link to jsfiddle, codepen or codesandbox?

**Comment by linkesch** [comment]
this looks like an old issue. closing this for no activity.

**Comment by selrond** [comment]
> > @orthes HOW COME THIS DOESN'T WORK ON NODE 0.1.14?????
> 
> @selrond can't repro. works on my machine. link to jsfiddle, codepen or codesandbox?

@orthes Here's a [codesandbox](https://codesandbox.io/s/broken-link-because-why-tf-not)

**Comment by selrond** [comment]
**selrond** added the `stale` label just now via **Useless bot**
